version: '3.8'

services:

  celery:
    build: .
    command: celery -A utils.celery_worker.celery_app worker --loglevel=info -P gevent
    volumes:
      - .:/app
    environment:
      - REDIS_URL=${REDIS_URL}

  fastapi:
    build: .
    command: uvicorn realmain:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - celery
    environment:
      - REDIS_URL=${REDIS_URL}

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: